modLoader="javafml"
loaderVersion="[35,)"
license="GPLv3"
[[mods]]
modId="chunksurvey"
version="${file.jarVersion}"
displayName="Chunk Survey"
authors="senox13"
description='''
Provides a simple command for counting the occurrences of a block in the world
'''
[[dependencies.chunksurvey]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chunksurvey]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
